name: budpay_flutter
description: Flutter budpay can be used to payment integration, bills payments, fast and automated transfers, and lot more. You can also generate virtual banks accounts, send money to your friends and families via bank transfer. It's also include a standardCheckout payment system.
version: 0.0.3
homepage: https://github.com/Ibnyahyah/budpay_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

keywords:
  - Payment Gateway
  - Bills payment
  - Airtime
  - Internet
  - Verification
  - Flutter
  - Flutter Budpay
  - Dart
  - Budpay Flutter
  - Budpay Payment Gateway
  - Flutter Budpay Payment Gateway
