name: budpay_flutter
description: A Flutter plugin for make paymen, integrating payment ways for end users, airtime purchasing and lots more.
version: 0.0.4
homepage: https://github.com/Ibnyahyah/budpay_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

keywords:
  - Payment Gateway
  - Bills payment
  - Airtime
  - Internet
  - Verification
  - Flutter
  - Flutter Budpay
  - Dart
  - Budpay Flutter
  - Budpay Payment Gateway
  - Flutter Budpay Payment Gateway
